RES_TOKEN_POS = {
    "coal": [
        (32, 743),
        (51, 743),
        (69, 743),
        (94, 743),
        (113, 743),
        (131, 743),
        (156, 743),
        (175, 743),
        (193, 743),
        (218, 743),
        (237, 743),
        (255, 743),
        (280, 743),
        (299, 743),
        (317, 743),
        (342, 743),
        (359, 743),
        (377, 743),
        (404, 743),
        (422, 743),
        (440, 743),
        (463, 743),
        (482, 743),
        (500, 743),
    ],
    "trash": [
        (32, 777),
        (51, 777),
        (69, 777),
        (94, 777),
        (113, 777),
        (131, 777),
        (156, 777),
        (175, 777),
        (193, 777),
        (218, 777),
        (237, 777),
        (255, 777),
        (280, 777),
        (299, 777),
        (317, 777),
        (342, 777),
        (359, 777),
        (377, 777),
        (404, 777),
        (422, 777),
        (440, 777),
        (463, 777),
        (482, 777),
        (500, 777),
    ],
    "oil": [
        (30, 761),
        (44, 761),
        (56, 761),
        (92, 761),
        (106, 761),
        (118, 761),
        (154, 761),
        (168, 761),
        (180, 761),
        (216, 761),
        (230, 761),
        (242, 761),
        (278, 761),
        (292, 761),
        (304, 761),
        (340, 761),
        (352, 761),
        (364, 761),
        (402, 761),
        (415, 761),
        (427, 761),
        (461, 761),
        (475, 761),
        (487, 761),
    ],
    "uranium": [
        (71, 761),
        (133, 761),
        (195, 761),
        (257, 761),
        (319, 761),
        (379, 761),
        (442, 761),
        (502, 761),
        (525, 748),
        (550, 748),
        (525, 776),
        (550, 776),
    ],
}

PHASES = ["Auction", "Resources", "Houses", "Bureaucracy"]

REGION_LIMITS = {2: 3, 3: 3, 4: 4, 5: 5, 6: 5}

CITIES = {
    "Flensburg": {"region": "Green", "pos": (241, 26), "neighbors": [["Kiel", 4]]},
    "Kiel": {
        "region": "Green",
        "pos": (271, 75),
        "neighbors": [["Flensburg", 4], ["Lubeck", 4], ["Hamburg", 8]],
    },
    "Hamburg": {
        "region": "Green",
        "pos": (267, 149),
        "neighbors": [
            ["Kiel", 8],
            ["Lubeck", 6],
            ["Schwerin", 8],
            ["Bremen", 11],
            ["Cuxhaven", 11],
            ["Hannover", 17],
        ],
    },
    "Bremen": {
        "region": "Green",
        "pos": (210, 197),
        "neighbors": [
            ["Hamburg", 11],
            ["Cuxhaven", 8],
            ["Wilhelmshaven", 11],
            ["Osnabruck", 11],
            ["Hannover", 10],
        ],
    },
    "Cuxhaven": {
        "region": "Green",
        "pos": (200, 119),
        "neighbors": [["Hamburg", 11], ["Bremen", 8]],
    },
    "Wilhelmshaven": {
        "region": "Green",
        "pos": (161, 149),
        "neighbors": [["Osnabruck", 14], ["Bremen", 11]],
    },
    "Hannover": {
        "region": "Green",
        "pos": (268, 268),
        "neighbors": [
            ["Hamburg", 17],
            ["Bremen", 10],
            ["Osnabruck", 16],
            ["Kassel", 15],
            ["Erfurt", 19],
            ["Magdeburg", 15],
            ["Schwerin", 19],
        ],
    },
    "Lubeck": {
        "region": "Brown",
        "pos": (314, 108),
        "neighbors": [["Kiel", 4], ["Hamburg", 6], ["Schwerin", 6]],
    },
    "Schwerin": {
        "region": "Brown",
        "pos": (353, 153),
        "neighbors": [
            ["Lubeck", 6],
            ["Rostock", 6],
            ["Hamburg", 8],
            ["Magdeburg", 16],
            ["Hannover", 19],
            ["Torgelow", 19],
            ["Berlin", 18],
        ],
    },
    "Rostock": {
        "region": "Brown",
        "pos": (388, 90),
        "neighbors": [["Schwerin", 6], ["Torgelow", 19]],
    },
    "Torgelow": {
        "region": "Brown",
        "pos": (498, 148),
        "neighbors": [["Rostock", 19], ["Schwerin", 19], ["Berlin", 15]],
    },
    "Magdeburg": {
        "region": "Brown",
        "pos": (374, 274),
        "neighbors": [
            ["Hannover", 15],
            ["Schwerin", 16],
            ["Berlin", 10],
            ["Halle", 11],
        ],
    },
    "Berlin": {
        "region": "Brown",
        "pos": (460, 251),
        "neighbors": [
            ["Torgelow", 15],
            ["Schwerin", 18],
            ["Magdeburg", 10],
            ["Halle", 17],
            ["FrankfurtO", 6],
        ],
    },
    "FrankfurtO": {
        "region": "Brown",
        "pos": (521, 269),
        "neighbors": [["Berlin", 6], ["Leipzig", 21], ["Dresden", 16]],
    },
    "Osnabruck": {
        "region": "Red",
        "pos": (165, 256),
        "neighbors": [
            ["Bremen", 11],
            ["Hannover", 16],
            ["Munster", 7],
            ["Wilhelmshaven", 14],
            ["Kassel", 20]
        ],
    },
    "Munster": {
        "region": "Red",
        "pos": (133, 303),
        "neighbors": [["Osnabruck", 7], ["Essen", 6], ["Dortmund", 2]],
    },
    "Essen": {
        "region": "Red",
        "pos": (91, 337),
        "neighbors": [
            ["Munster", 6],
            ["Dortmund", 4],
            ["Duisburg", 0],
            ["Duesseldorf", 2],
        ],
    },
    "Dortmund": {
        "region": "Red",
        "pos": (142, 360),
        "neighbors": [
            ["Munster", 2],
            ["Essen", 4],
            ["Koln", 10],
            ["Kassel", 18],
            ["FrankfurtM", 20],
        ],
    },
    "Duisburg": {
        "region": "Red",
        "pos": (55, 324),
        "neighbors": [
            ["Essen", 0],
        ],
    },
    "Duesseldorf": {
        "region": "Red",
        "pos": (64, 381),
        "neighbors": [["Essen", 2], ["Koln", 4], ["Aachen", 9]],
    },
    "Kassel": {
        "region": "Red",
        "pos": (239, 372),
        "neighbors": [
            ["Hannover", 15],
            ["Osnabruck", 20],
            ["Dortmund", 18],
            ["FrankfurtM", 13],
            ["Fulda", 8],
            ["Erfurt", 15],
        ],
    },
    "Koln": {
        "region": "Blue",
        "pos": (103, 420),
        "neighbors": [
            ["Dortmund", 10],
            ["Duesseldorf", 4],
            ["Aachen", 7],
            ["Trier", 20],
            ["Wiesbaden", 21],
        ],
    },
    "Aachen": {
        "region": "Blue",
        "pos": (47, 436),
        "neighbors": [["Koln", 7], ["Duesseldorf", 9], ["Trier", 19]],
    },
    "FrankfurtM": {
        "region": "Blue",
        "pos": (202, 478),
        "neighbors": [
            ["Kassel", 13],
            ["Dortmund", 20],
            ["Wiesbaden", 0],
            ["Wuerzburg", 13],
            ["Fulda", 8],
        ],
    },
    "Wiesbaden": {
        "region": "Blue",
        "pos": (166, 494),
        "neighbors": [
            ["FrankfurtM", 0],
            ["Koln", 21],
            ["Trier", 18],
            ["Saarbrucken", 10],
            ["Mannheim", 11],
        ],
    },
    "Trier": {
        "region": "Blue",
        "pos": (70, 524),
        "neighbors": [
            ["Koln", 20],
            ["Aachen", 19],
            ["Wiesbaden", 18],
            ["Saarbrucken", 11],
        ],
    },
    "Saarbrucken": {
        "region": "Blue",
        "pos": (120, 580),
        "neighbors": [
            ["Trier", 11],
            ["Wiesbaden", 10],
            ["Mannheim", 11],
            ["Stuttgart", 17],
        ],
    },
    "Mannheim": {
        "region": "Blue",
        "pos": (197, 565),
        "neighbors": [
            ["Wiesbaden", 11],
            ["Saarbrucken", 11],
            ["Stuttgart", 6],
            ["Wuerzburg", 10],
        ],
    },
    "Dresden": {
        "region": "Yellow",
        "pos": (498, 405),
        "neighbors": [["FrankfurtO", 16], ["Leipzig", 13], ["Erfurt", 19]],
    },
    "Fulda": {
        "region": "Yellow",
        "pos": (266, 445),
        "neighbors": [
            ["Kassel", 8],
            ["FrankfurtM", 8],
            ["Wuerzburg", 11],
            ["Erfurt", 13],
        ],
    },
    "Erfurt": {
        "region": "Yellow",
        "pos": (342, 402),
        "neighbors": [
            ["Hannover", 19],
            ["Kassel", 15],
            ["Fulda", 13],
            ["Nurnberg", 21],
            ["Dresden", 19],
            ["Halle", 6],
        ],
    },
    "Halle": {
        "region": "Yellow",
        "pos": (384, 350),
        "neighbors": [["Magdeburg", 11], ["Erfurt", 6], ["Leipzig", 0], ["Berlin", 17]],
    },
    "Leipzig": {
        "region": "Yellow",
        "pos": (416, 373),
        "neighbors": [["Halle", 0], ["Dresden", 13], ["FrankfurtO", 21]],
    },
    "Wuerzburg": {
        "region": "Yellow",
        "pos": (276, 521),
        "neighbors": [
            ["Fulda", 11],
            ["FrankfurtM", 13],
            ["Mannheim", 10],
            ["Stuttgart", 12],
            ["Augsburg", 19],
            ["Nurnberg", 8],
        ],
    },
    "Nurnberg": {
        "region": "Yellow",
        "pos": (341, 553),
        "neighbors": [
            ["Erfurt", 21],
            ["Wuerzburg", 8],
            ["Augsburg", 18],
            ["Regensburg", 12],
        ],
    },
    "Stuttgart": {
        "region": "Purple",
        "pos": (215, 626),
        "neighbors": [
            ["Mannheim", 6],
            ["Saarbrucken", 17],
            ["Freiburg", 16],
            ["Konstanz", 16],
            ["Augsburg", 15],
            ["Wuerzburg", 12],
        ],
    },
    "Freiburg": {
        "region": "Purple",
        "pos": (147, 685),
        "neighbors": [["Stuttgart", 16], ["Konstanz", 14]],
    },
    "Konstanz": {
        "region": "Purple",
        "pos": (214, 718),
        "neighbors": [["Stuttgart", 16], ["Freiburg", 14], ["Augsburg", 17]],
    },
    "Augsburg": {
        "region": "Purple",
        "pos": (311, 647),
        "neighbors": [
            ["Wuerzburg", 19],
            ["Stuttgart", 15],
            ["Konstanz", 17],
            ["Muenchen", 6],
            ["Regensburg", 13],
            ["Nurnberg", 18],
        ],
    },
    "Muenchen": {
        "region": "Purple",
        "pos": (368, 687),
        "neighbors": [["Augsburg", 6], ["Passau", 14], ["Regensburg", 10]],
    },
    "Regensburg": {
        "region": "Purple",
        "pos": (387, 600),
        "neighbors": [
            ["Nurnberg", 12],
            ["Augsburg", 13],
            ["Muenchen", 10],
            ["Passau", 12],
        ],
    },
    "Passau": {
        "region": "Purple",
        "pos": (475, 641),
        "neighbors": [["Regensburg", 12], ["Muenchen", 14]],
    },
}
